stages:
  - test
  - deploy

image: ruby:2.4.1

before_script:
  - ruby --version
  - gem --version
  - bundle --version
  - bundle install

sanitize:
  stage: test
  script:
    - bundle exec jekyll build -d _test
    - "! grep -rnw ./_test -e $NO_BUNNY_ALLOWED || exit 1"
    - "! grep -rnw ./_test -e $NO_CHINO_ALLOWED || exit 1"
    - "! grep -rnw ./_test -e $NO_MISTAKES_ALLOWED || exit 1"
    - "! git log | grep -e $NO_BUNNY_ALLOWED || exit 1"
    - "! git log | grep -e $NO_CHINO_ALLOWED || exit 1"

deploy:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    refs:
      - production
