image: ruby:2.4.1

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - ruby --version
  - gem --version
  - bundle --version
  - bundle install

sanitize:
  stage: test
  script:
    - bundle exec jekyll build -d _test
    - "! grep -rnw ./_test -e $NO_BUNNY_ALLOWED || exit 1"
    - "! grep -rnw ./_test -e $NO_CHINO_ALLOWED || exit 1"
    - "! git log | grep -e $NO_BUNNY_ALLOWED || exit 1"
    - "! git log | grep -e $NO_CHINO_ALLOWED || exit 1"
  except:
    - /^post-.*$/

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - production
