image: ruby:2.4.1

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - ruby --version
  - gem --version
  - bundle --version

jekyll_build:
  stage: build
  script:
    - bundle install
    - bundle exec jekyll build -d _test
  artifacts:
    paths:
      - _test
  except:
    - /^post-.*$/

sanitize:
  stage: test
  script:
    - "! grep -rnw ./_test -e $NO_BUNNY_ALLOWED || exit 1"
    - "! grep -rnw ./_test -e $NO_CHINO_ALLOWED || exit 1"
    - "! git log | grep -e $NO_BUNNY_ALLOWED || exit 1"
    - "! git log | grep -e $NO_CHINO_ALLOWED || exit 1"
  dependencies:
    - jekyll_build

pages:
  stage: deploy
  script:
    - mv _test public
  artifacts:
    paths:
      - public
  only:
    - production
