session_name: devpro
start_directory: ./
windows:
  - layout: main-vertical
    panes:
    - vi
    - shell_command:
      - tmux setw main-pane-width 140
      - tmux selectl main-vertical
      - clear
      - ./start-server
